

FPS


LOCAL - Plate 9D41, Latency 4.599288, FPS 1.000000, RES 1080
LOCAL - Plate 1Y31, Latency 4.568988, FPS 1.000000, RES 1080
LOCAL - Plate E23GLV, Latency 4.653984, FPS 1.000000, RES 1080
LOCAL - Plate OL4958J, Latency 4.538696, FPS 1.000000, RES 1080
LOCAL - Plate AP118Y, Latency 4.547720, FPS 1.000000, RES 1080
LOCAL - Plate T687892C, Latency 4.593342, FPS 1.000000, RES 1080
LOCAL - Plate ROAD70, Latency 4.521065, FPS 1.000000, RES 1080
LOCAL - Plate T635970C, Latency 4.519124, FPS 1.000000, RES 1080
LOCAL - Plate T666363C, Latency 4.471287, FPS 1.000000, RES 1080
LOCAL - Plate 4M38, Latency 4.389358, FPS 1.000000, RES 1080
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/skvideo/io/ffmpeg.py", line 267, in _read_frame_data
    assert len(arr) == framesize
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 55, in <module>
    alpr.find(PLATES)
  File "/Local.py", line 23, in find
    for frame in videodata:
  File "/usr/local/lib/python3.4/dist-packages/skvideo/io/io.py", line 253, in vreader
    for frame in reader.nextFrame():
  File "/usr/local/lib/python3.4/dist-packages/skvideo/io/ffmpeg.py", line 293, in nextFrame
    yield self._readFrame()
  File "/usr/local/lib/python3.4/dist-packages/skvideo/io/ffmpeg.py", line 277, in _readFrame
    s = self._read_frame_data()
  File "/usr/local/lib/python3.4/dist-packages/skvideo/io/ffmpeg.py", line 271, in _read_frame_data
    raise RuntimeError("%s" % (err1,))
RuntimeError
